use_frameworks!

target 'heatshrink-objc_Example' do
  pod 'heatshrink-objc', :path => '../'

end

target 'heatshrink-objc_Tests' do
    inherit! :search_paths
    pod 'heatshrink-objc', :path => '../'
    pod 'Expecta'
end
