use_frameworks!

target 'heatshrink-objc_Example' do
  pod 'heatshrink-objc', :path => '../'

  target 'heatshrink-objc_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
